export const LAYER_TYPE_DATASET = 'DATASET'
export const LAYER_TYPE_CATALOG = 'CATALOG'

export const FIELD_TYPE_SPATIAL_ATTRIBUTE = 'SPATIAL_ATTRIBUTE'
export const FIELD_TYPE_ATTRIBUTE = 'ATTRIBUTE'
export const FIELD_TYPE_MEASURE = 'MEASURE'
